import turtle

turtle.pensize(3)
turtle.penup()
turtle.goto(-200, -50)
turtle.pendown()
turtle.begin_fill()
turtle.speed(2)
turtle.circle(40, steps = 3)
turtle.color("red")
turtle.end_fill()

turtle.color("black")
turtle.penup()
turtle.goto(-100, -50)
turtle.pendown()
turtle.begin_fill()
turtle.circle(40, steps = 4)
turtle.color("blue")
turtle.end_fill()

turtle.color("black")
turtle.penup()
turtle.goto(0, -50)
turtle.pendown()
turtle.begin_fill()
turtle.circle(40, steps = 5)
turtle.color("green")
turtle.end_fill()

turtle.color("black")
turtle.penup()
turtle.goto(100, -50)
turtle.pendown()
turtle.begin_fill()
turtle.circle(40, steps = 6)
turtle.color("yellow")
turtle.end_fill()

turtle.color("black")
turtle.penup()
turtle.goto(200, -50)
turtle.pendown()
turtle.begin_fill()
turtle.circle(40)
turtle.color("purple")
turtle.end_fill()

turtle.color("pink")
turtle.penup()
turtle.goto(-100, 50)
turtle.pendown()
turtle.write("Cool Colorful Shapes", font = ("Times", 18, "bold"))
turtle.hideturtle()

turtle.done()
